### PR TITLE
Script updates and documentation interlinking 

### PR DESCRIPTION
**Pull request by ankicabarisic**
There were parts of code which script templates are using which were still in Ali's private repository so they were moved into our project. There are several other scripts which are not used by current templates which I did not move and can be seen [here](https://github.com/alijawadfahs/scripts/tree/main/nebulous).
In a case, if it is to also move them, let me know to do so. 

Also, the endpoints documentation was interlinked with new Cluster endpoints documentation.

### CODE REVIEW

**Comment by fviale** [comment]
@ankicabarisic you could extract the comments in the json section as I mentioned last time. There are not many md files

**Comment by ankicabarisic** [comment]
hi, I added it as a task for the next PR on the ticket: https://trello.com/c/Hup4Ymj3 which will also include the overview of all endpoints and interlinking the nebulous scenario I am currently writing.

**Comment by ankicabarisic** [comment]
Note that yes, there are 10 .md files, but 52 endpoints, of which at least half have JSON files containing the comments.
I guess this improvement will be PR by itself.

The current PR is to have the k8s script templates independent of any other repos (out of AE).

**Comment by fviale** [comment]
@ankicabarisic ok I didn't see as many, in that case you can do that in another PR

**Review by fviale — APPROVED** [review]

**Pull request merged**
